---
abstract: 'RT-Extension-Assets-AppleGSX Extension'
author:
  - 'Best Practical Solutions <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Assets-AppleGSX
no_index:
  directory:
    - etc
    - html
    - inc
requires:
  Class::Accessor::Fast: 0
  IO::Socket::SSL: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Net::SSLeay: 0
  XML::SAX: 0
  XML::Simple: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '2.03'
x_module_install_rtx_version: '0.42'
x_requires_rt: 4.0.0
